// Copyright (C) Tenacom and Contributors. Licensed under the MIT license.
// See the LICENSE file in the project root for full license information.

using System.Text;
using Buildvana.Sdk.SourceGenerators.Internal;
using Microsoft.CodeAnalysis;

namespace Buildvana.Sdk.SourceGenerators;

[Generator(LanguageNames.CSharp, LanguageNames.VisualBasic, LanguageNames.FSharp)]
public class AdditionalAssemblyInfoGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var languageProvider = context.ParseOptionsProvider.Select((p, _) => p.Language);
        var attributeValuesProvider = context
                                     .AnalyzerConfigOptionsProvider
                                     .Select((p, _)
                                          => new AdditionalAssemblyInfoValues(
                                              p.GetBooleanMSBuildProperty("CLSCompliant"),
                                              p.GetBooleanMSBuildProperty("ComVisible")));

        var finalProvider = languageProvider.Combine(attributeValuesProvider);
        context.RegisterSourceOutput(finalProvider, (spc, data) =>
        {
            var (language, values) = data;
            var sb = new StringBuilder()
                    .AppendAutoGenerated(language)
                    .AppendBooleanAssemblyAttribute(language, "System.CLSCompliant", values.CLSCompliant)
                    .AppendBooleanAssemblyAttribute(language, "System.Runtime.InteropServices.ComVisible", values.ComVisible);

            spc.AddSource("BV_AssemblyAttributes", sb.ToString());
        });
    }
}
