// <auto-generated>
//   This file has been added automatically to your project by Buildvana SDK.
//   Please see https://github.com/Buildvana/Buildvana.Sdk for more information.
// </auto-generated>

using System;
using System.Diagnostics.CodeAnalysis;

[ExcludeFromCodeCoverage]
[AttributeUsage(AttributeTargets.Parameter, AllowMultiple=false, Inherited=false)]
internal sealed class ValidatedNotNullAttribute : Attribute
{
}
