// <auto-generated />

using global::System;

[ExcludeFromCodeCoverage]
[AttributeUsage(AttributeTargets.Parameter, AllowMultiple=false, Inherited=false)]
internal sealed class ValidatedNotNullAttribute : Attribute
{
}
