// <auto-generated />

using System;
using System.Diagnostics.CodeAnalysis;

[ExcludeFromCodeCoverage]
[AttributeUsage(AttributeTargets.Parameter, AllowMultiple=false, Inherited=false)]
internal sealed class ValidatedNotNullAttribute : Attribute
{
}
