// -----------------------------------------------------------------------------------
// Copyright (C) Riccardo De Agostini and Buildvana contributors. All rights reserved.
// Licensed under the MIT license.
// See LICENSE file in the project root for full license information.
//
// Part of this file may be third-party code, distributed under a compatible license.
// See THIRD-PARTY-NOTICES file in the project root for third-party copyright notices.
// -----------------------------------------------------------------------------------

using System.Text;

namespace Buildvana.Sdk.Tasks.Internal
{
    public abstract class CodeBuilder
    {
        private readonly StringBuilder _sb;

        protected CodeBuilder()
        {
            _sb = new StringBuilder();
            AtStartOfLine = true;
            LineComment("<auto-generated />");
        }

        public bool AtStartOfLine { get; private set; }

        protected abstract string LineCommentPrefix { get; }

        public void Text(char ch)
        {
            _ = _sb.Append(ch);
            AtStartOfLine = false;
        }

        public void Text(string code)
        {
            _ = _sb.Append(code);
            AtStartOfLine = false;
        }

        public void Text(string code, int startIndex, int count)
        {
            _ = _sb.Append(code, startIndex, count);
            AtStartOfLine = false;
        }

        public abstract void QuotedText(string str);

        public void NewLine()
        {
            if (!AtStartOfLine)
            {
                _ = _sb.AppendLine();
                AtStartOfLine = true;
            }
        }

        public void NewLine(string code)
        {
            NewLine();
            Text(code);
        }

        public void LineComment(string comment)
        {
            NewLine(LineCommentPrefix);
            Text(comment);
            NewLine();
        }

        public string GetGeneratedCode() => _sb.ToString();
    }
}