// <auto-generated>
//   This file has been added automatically to your project by Buildvana SDK.
//   Please see https://github.com/Buildvana/Buildvana.Sdk for more information.
// </auto-generated>

// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.
// See the LICENSE file in the project root for more information.

#if !NET5_0_OR_GREATER

using System.Diagnostics.CodeAnalysis;

namespace System.Runtime.CompilerServices;

/// <summary>
/// Used to indicate to the compiler that the <c>.locals init</c> flag should not be set in method headers.
/// </summary>
/// <remarks>Internal copy of the .NET 5 attribute.</remarks>
[ExcludeFromCodeCoverage]
[AttributeUsage(
    AttributeTargets.Module |
    AttributeTargets.Class |
    AttributeTargets.Struct |
    AttributeTargets.Interface |
    AttributeTargets.Constructor |
    AttributeTargets.Method |
    AttributeTargets.Property |
    AttributeTargets.Event,
    Inherited = false)]
internal sealed class SkipLocalsInitAttribute : Attribute
{
}

#endif
